import os
import shutil

# Web directory for UI extensions
WEB_DIRECTORY = "./web"

from .nodes import NODE_CLASS_MAPPINGS as CORE_CLASS_MAPPINGS
from .nodes import NODE_DISPLAY_NAME_MAPPINGS as CORE_DISPLAY_NAME_MAPPINGS

from .image_utils import NODE_CLASS_MAPPINGS as IMAGES_CLASS_MAPPINGS
from .image_utils import NODE_DISPLAY_NAME_MAPPINGS as IMAGES_DISPLAY_NAME_MAPPINGS

from .JR_LoadImageBatch import NODE_CLASS_MAPPINGS as LOAD_BATCH_CLASS_MAPPINGS
from .JR_LoadImageBatch import NODE_DISPLAY_NAME_MAPPINGS as LOAD_BATCH_DISPLAY_NAME_MAPPINGS

from .filebrowser import NODE_CLASS_MAPPINGS as FILEBROWSER_CLASS_MAPPINGS
from .filebrowser import NODE_DISPLAY_NAME_MAPPINGS as FILEBROWSER_DISPLAY_NAME_MAPPINGS

NODE_CLASS_MAPPINGS = {
    **CORE_CLASS_MAPPINGS,
    **IMAGES_CLASS_MAPPINGS,
    **LOAD_BATCH_CLASS_MAPPINGS,
    **FILEBROWSER_CLASS_MAPPINGS
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **CORE_DISPLAY_NAME_MAPPINGS,
    **IMAGES_DISPLAY_NAME_MAPPINGS,
    **LOAD_BATCH_DISPLAY_NAME_MAPPINGS,
    **FILEBROWSER_DISPLAY_NAME_MAPPINGS
}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS', 'WEB_DIRECTORY']
